# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170705_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
