# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_commentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.PostModel')),
            ],
        ),
    ]
